# (C) Copyright 2015 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := zero-sugar.o \
          uart_init.o \
          wifi_init.o \
          epd_init.o \
          lcd_init.o \
          digitizer_init.o \
          charger_init.o \
          serial_download_trap.o \
          ../../freescale/common/mmc.o
