# (C) Copyright 2015 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y  := zero-sugar.o \
          uart_init.o \
          epd_pmic_init.o \
          epd_display_init.o \
          digitizer_init.o \
          charger_init.o \
          mmc_tools.o \
          serial_download_trap.o \
          jump_rom_usb_download.o \
          ../../freescale/common/mmc.o
